### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by uloveqian2021** [hulucky1102/Task-Oriented-Dialogue-Systems#1]
您好，能提供ner_model 部分训练数据或者数据样例吗

**Comment by hulucky1102** [comment]
数据格式是SMP格式

**Comment by uloveqian2021** [comment]
> 数据格式是SMP格式
感谢！！！，还有一个问题， DM_model 中的all_stories.yml 是怎么样的格式呢，

**Comment by hulucky1102** [comment]
参考rasa中story的数据格式。

**Comment by hulucky1102** [comment]
# 以防表述有误，发个样例便于理解

  # story: 打开抽油烟机|强力模式
- steps:
  - entities:
    - operation: 打开
    - device: 抽油烟机
    intent: Control-RangHood_State
  - action: Control-RangHood_State
  - entities:
    - mode: 强力模式
    intent: inform_mode
  - action: Control-RangHood_Mode
